language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
before_script:
  - npm run tslint-check
script:
  - npm run lint:ci
  - npm run build:new
  - npm run ci